name: Daily Check-in

on:
  schedule:
    - cron: '0 1 * * *'  # 每天1点 UTC 时间执行
  workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9.19'

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install --with-deps firefox

      - name: Execute script
        env:
          SENDKEY: ${{ secrets.SENDKEY }}
        run: |
          python main.py

      - name: Send Telegram Notification
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_USERID: ${{ secrets.TELEGRAM_USERID }}
        if: ${{ success() }}
        run: |
          curl -s -X POST "https://sctapi.ftqq.com/${{ secrets.SENDKEY }}.send"  \
          -H 'Content-Type: application/json;charset=utf-8' \
          -d desp=HTML \
          -d title="<b>LINUX DO</b> 每日签到成功完成"

      - name: Send Failure Notification
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_USERID: ${{ secrets.TELEGRAM_USERID }}
        if: ${{ failure() }}
        run: |
          curl -s -X POST "https://sctapi.ftqq.com/${{ secrets.SENDKEY }}.send" \
          -H 'Content-Type: application/json;charset=utf-8' \
          -d desp=HTML \
          -d title="❌ <b>LINUX DO</b> 每日签到失败"

      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 10
          keep_minimum_runs: 6
